#+TITLE:ADA-NCEPH Data Access Procedure 
#+AUTHOR: Ivan Hanigan and Steven McEachern
#+email: ivan.hanigan@anu.edu.au
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LATEX: \tableofcontents
#+LATEX_HEADER: \usepackage{pdfpages}

#\clearpage
* COMMENT graphviz code
#+name:flowdiagram
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ###########################################################################
  # newnode: mortalityAccessFlowDiagram
  # REQUIRES THE DISENTANGLE REPO FROM https://github.com/ivanhanigan/disentangle
  # Clone into a tools directory, or change the following line
  source('~/tools/disentangle/src/newnode.r')
#+end_src
* COMMENT TODOLIST
** TODO Ivan send graphivis lowlevel versions to Steve by noon Fri (also NCEPH policy)
** TODO Steve review and comment
** TODO Ivan to revise lucidchart highlevel version on Mon-Tues
** TODO Ivan finalise and send to BDM by Wed-ish, CC Steve
** TODO Ivan Test BDM survey
*** intro
From: Jo-Marie Moore [jo.moore@abs.gov.au]
Sent: 23 October 2012 16:31
To: Ivan Hanigan
Subject: RE: Registry of Births, Deaths and Marriages User Survey testing [SEC=UNCLASSIFIED]

Hi Ivan,

The Registry User survey is ready for testing.  The survey covers COD data, but also Registry data more generally.  Once tested it will be sent to all our Registry data users (in all States and Territories) and those on our COD URF communications register.
*** survey
Please follow the link and complete the survey as if you were really responding on behalf of your agency.  
https://www.surveymonkey.com/s/registrydatasurvey
*** QA
Please remember to record the following:
1. How long it the survey took to complete.
35 minutes

2. Would you know who you should also forward the survey onto within your agency and who would you forward this to outside of your agency (if any).
Deputy Director at the Australian Data Archives, the Data Manager at the Australian Demographic and Social Research Intitute, the Data Manager at the Centre for Mental Health Research, The Population Health Research Network, the Secure Unified Research Environment (SURE) team at the Sax Institute.

3. If any of the questions did not make sense (if you think this is going to have a major impact on our survey results, if you have any suggested improvements for the question)

Q4.4 Agency has organisational legislative protections for the access and use of data
The University has a policy called the 'Responsible Practice of Research' which makes statements about appropriate access and use of data, and that references the NHMRC guidelines on human research.  Not sure if this counts as organisational legislation though?
4.6 Restricted access to data store or IT access approval process.
perhaps 'is access to the data store restricted with IT access approval processes in place?'
4.9 in secure remote server environments the passes would be worn by IT infrastructure staff, the researchers in a different building would not need these but do work in locked rooms and password protected computers.  I answered for the researchers, but out IT Infrastructure server room is swipecard entry only.
4.10 ANU operates a virtual machine (VM) cluster which means that individual servers (VMs) are connected.  They operate like seperate computers so I answered yes.


4. Any spelling or other errors
Q6.9 To make aggregate dta tables available publicly
should be data

5. Any other suggestions you have as you work through the survey
No

*** respond
Please let me know by email to both my QLD Registry and ABS email addresses when you have completed the survey, so we can also test running aggregated reports.  

We would really appreciate your feedback as soon as possible.

Thanks

Jo-Marie Moore

Assistant Director

(Please note: I work Tuesday at the ABS and Monday, Wednesday-Friday at the QLD Registry of Births, Deaths and Marriages)

Outposted Officer - QLD Births, Deaths and Marriages  |  Health & Vitals Branch  |  Australian Bureau of Statistics

(P) (07) 3222 6080   (M) 0437 1343 77  (F) (07) 3222 6299

(E) jo.moore@abs.gov.au  (W)  www.abs.gov.au

NatStats 2013 Conference, Brisbane Convention and Exhibition Centre, 12-14 March 2013
Early bird registrations close 31 October 2012
www.nss.gov.au/blog/natstats.nsf 

* Introduction 
The aim of this document is to describe the procedure for accessing restricted health data through the proposed ANU Secure Data Hub, administered by the ADA and NCEPH.

The following descibes procedures and processes for three different agents in the system, with different roles:
- Users,
- User Administrators, and 
- Data Administrators.

The User and Data information that is used to control the actions of the system are stored in a Database at ANU referred to as the ANU-User-DB.
\newpage

* Getting Access
The "Getting Access" procedure to help users apply for and gain access to mortality data is shown in Figure 1, and a more detailed description of the process is shown in the Appendix, Figure 4. The process is a set of formally defined steps that are designed to move the User through two general stages:
- Requesting data: guiding the researcher through the process of (a) gaining Ethics Approval from a Human Research Ethics Committee, and (b) Project Level Approval from the Registrar of Births, Deaths and Marriages.
- Providing data: provision of a confidentialised (often aggregated) dataset in an appropriately secured manner such as access to remote secure servers or encrypted archives accessed on local disk media, with security determined by (a) the nature of the data and (b) any project management related criteria.

#\includepdf{DataAccessFlowDiagram-GettingAccess.pdf}
\begin{figure}[!h]
\centering
\includegraphics[width=1\textwidth]{DataAccessFlowDiagram-GettingAccess-general.png}
\caption{Flow Diagram of Getting Access}
\label{fig:DataAccessFlowDiagram-GettingAccess}
\end{figure}
\clearpage

** COMMENT src
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ###########################################################################
  # Getting access
  
  nodes <- newnode(name='Browse Catalogue',
                   inputs = 'Search for Data',
                   outputs = 'Request Access',
                   newgraph = T
                   )
  ## NEEDS ETHICS COMMITTEE PROCESS HERE
  
  nodes <- newnode(name= 'Get Ethics Committee Approval',
                  inputs='Request Access',
                   outputs = 'Ethics Committee Approves Project')
  
  nodes <- newnode(name= 'Add Study Description in ANU-User-DB',
                  inputs= 'Ethics Committee Approves Project'
                   )
  
  nodes <- newnode(name = 'Get BDM Committee Approval',
                   inputs = 'Add Study Description in ANU-User-DB'
                   )
  ## INSERT BDM APPROVAL PROCESS HERE
  
  nodes <- newnode(name='Approve Access',
                   inputs = 'Get BDM Committee Approval'
  
                   )
  
  nodes <- newnode(name='Deny Access',
                   inputs = 'Get BDM Committee Approval'
  
  )
  
  
  
  ###########################################################################
  # Provide data
  # nodes <- newnode(name='Add to Study Description in ANU-User-DB',
  #                  inputs='Request Access',
  #                  outputs= 'Review Application',
  #
  #                  )
  
  # notify approval
  
  nodes <- newnode(name='Notify User of Approval',
                   inputs='Approve Access',
                   outputs='Add Access Record in ANU-User-DB',
                   )
  
  # or record why not
  
  nodes <- newnode(name='Notify User of Non-approval',
                   inputs='Deny Access',
                   outputs='Note Reason in Study Description in ANU-User-DB',
                   )
  
  
  
  nodes <- newnode(name='Give access to Restricted Server', newgraph = F,
                   inputs = 'Add Access Record in ANU-User-DB'
                   )
  
  
  nodes <- newnode(name='Extract to Restricted Server', newgraph = F,
                   inputs = 'Give access to Restricted Server'
                   )
  
  nodes <- newnode(name= 'Store data extract in appropriate location', newgraph = F,
                   inputs = c('Extract to Restricted Server'),
                   outputs = c('Low Risk Data')
                   )
  
  nodes <- newnode(name = 'CSV',
                   inputs = 'Low Risk Data')
  
  nodes <- newnode(name = 'High Risk Data', outputs =
                   c('Database schema', 'Rstudio user workspace'),
                   inputs = 'Store data extract in appropriate location'
                   )
  
  nodes <- newnode(name= 'Add File Record to ANU-User-DB', newgraph = F,
                   inputs = c('CSV', 'Database schema', 'Rstudio user workspace'),
  
  
                   outputs = c('Notify User of Access')
  )
  
  nodes <- newnode(name = 'Modify file and access records in ANU-User-DB',
                   inputs = 'Notify User of Access')
  
#+end_src  
** COMMENT add colour
#+name:add-colour
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ###########################################################################
  # newnode: test-colour
  attrs <- list(node=list(shape="ellipse", fixedsize=FALSE))
  plot(nodes, attrs = attrs)
  nNodes <- length(nodes(nodes))
  nA <- list()
  nA$fillcolor <- rep('grey', nNodes)
  nA$shape <- rep("ellipse", nNodes)
  nA <- lapply(nA, function(x) { names(x) <- nodes(nodes); x})
  #nA
  #plot(nodes, nodeAttrs=nA, attrs = attrs)
  nodes(nodes)
  # USER
  nA$fillcolor[nodes(nodes)[1:4]] <- '#FB8072' #'#8DD3C7'
  # USER ADMIN
  nA$fillcolor[nodes(nodes)[c(6:7,10:13, 22:24)]] <- '#FFFFB3'
  # DATA ADMIN
  nA$fillcolor[nodes(nodes)[c(14:16, 18, 20, 21)]] <- '#BEBADA'
  # DECISIONS
  dec <- c(5,8:9, 17,19)
  nA$fillcolor[nodes(nodes)[dec]] <- 'white' 
  nA$shape[nodes(nodes)[dec]] <- 'box'
  
  plot(nodes, nodeAttrs=nA, attrs = attrs)
  legend('topleft', legend = c('User','User Admin', 'Data Admin','Decision'),
         pch = c(21,21,21,22), pt.cex = 1.5,
         pt.bg = c('#FB8072', '#FFFFB3', '#BEBADA', 'white')
         )
  
#+end_src

** COMMENT plot nodes
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r  :exports none :eval no   
    
  dev.copy2pdf(file='DataAccessFlowDiagram-GettingAccess.pdf')
  dev.off()
    
#+end_src


* Managing Access
Procedures for managing access are shown in Figure 2 (and in the Appendix, Figure 5). These activities are intended to maintain information on the current state of projects using the mortality data, and to report any changes in situation to the State Registries. The User Administrator is responsible for conduct of the "Managing Access" procedures.

The process is initiated by running a query on the ANU-User-DB to make a list of all Projects and Users, and then each Project is sent a reminder to report any changes in Project Status (sent annually to coincide with a similar reminder sent by the ANU Human Research Ethics Committee). The purpose of these reminders is to ensure that Project management plans continue to consider data security as a primary concern, even during long multi-year projects where many project management and staffing issues inevitably arise.

Once a response is received, the User Administrator then enters the relevant information into the ANU-User-DB, and if the project has been concluded will then iniitate the final "Ending Access" process.


\begin{figure}[!h]
\centering
\includegraphics[width=\textwidth]{DataAccessFlowDiagram-ManagingAccess-general.png}
\caption{Flow Diagram of Managing Access}
\label{fig:DataAccessFlowDiagram-ManagingAccess}
\end{figure}
\clearpage


** COMMENT src
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no 
  ###########################################################################
  # newnode Manage Access
  
  nodes <- newnode(name= 'List Current Users',
                   inputs = c('Modify file access record in ANU-User-DB'),
                   outputs = c('Email Users'),
                   newgraph = T
                   )
  
  nodes <- newnode(name= 'Receive Reminder',
                   inputs = c('Email Users')
  
                   )
  
  nodes <- newnode(name= 'Report Status',
                   inputs = c('Receive Reminder'),
                   outputs = c('No Change', 'Changed Status')
                   )
  
  
  nodes <- newnode(name= 'Input Response',
                   inputs = c('No Change', 'Changed Status'),
                   outputs = c('Write Report',
                   'Modify file access record in ANU-User-DB', 'Review Report'))
#+end_src
** COMMENT add colour
#+name:add-colour
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ###########################################################################
  # newnode: test-colour
  attrs <- list(node=list(shape="ellipse", fixedsize=FALSE))
  plot(nodes, attrs = attrs)
  nNodes <- length(nodes(nodes))
  nA <- list()
  nA$fillcolor <- rep('grey', nNodes)
  nA$shape <- rep("ellipse", nNodes)
  nA <- lapply(nA, function(x) { names(x) <- nodes(nodes); x})
  #nA
  #plot(nodes, nodeAttrs=nA, attrs = attrs)
  nodes(nodes)
  # USER
  nA$fillcolor[nodes(nodes)[4:5]] <- 'lightblue'
  # USER ADMIN
  nA$fillcolor[nodes(nodes)[c(1:3,8:10)]] <- 'darkgrey'
  # DATA ADMIN
  #nA$fillcolor[nodes(nodes)[c(14:16, 18, 20, 21)]] <- 'lightblue'
  # DECISIONS
  dec <- c(6:7)
  nA$fillcolor[nodes(nodes)[dec]] <- 'white'
  nA$shape[nodes(nodes)[dec]] <- 'box'
  
  plot(nodes, nodeAttrs=nA, attrs = attrs)
  legend('topleft', legend = c('User','User Admin', 'Decision'),
         pch = c(21,21,22),
         pt.bg = c('lightblue','darkgrey', 'white')
         )
  
#+end_src

** COMMENT plot nodes
#+name:plotnodes
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ################################################################
  # name:plotnodes
      dev.copy2pdf(file='DataAccessFlowDiagram-ManagingAccess.pdf')
      dev.off()
  
#+end_src



* Ending Access
The procedure for ending access aims to ensure that data are both securely and sustainably stored.  It is very important that files used for authorised projects are never re-used in un-authorised projects, but that future researchers may have the opportunity to create an authorised project and potentially replicate historical analyses.  This is an important part of reproducible research and the robust practice of scientific enquiry.


\begin{figure}[!h]
\centering
\includegraphics[width=\textwidth]{DataAccessFlowDiagram-EndAccess-general.png}
\caption{Flow Diagram for Ending Access}
\label{fig:DataAccessFlowDiagram-EndAccess}
\end{figure}
\clearpage

** COMMENT src
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no   
  ###########################################################################
  # newnode End Access
  nodes <- newnode(name= 'Query Registered End Dates',
                   inputs = c('Start Periodic Review'),
                   outputs = c('Send Prompt to Users'),
                   newgraph = T)
  
  nodes <- newnode(name= 'User Receives Prompt',
                   inputs = c('Send Prompt to Users')
                   )
  
  nodes <- newnode(name= 'User Reviews Status',
                   inputs = c('User Receives Prompt'),
                   outputs = c('Project Continuing', 'Project Concluded')
                   )
  
  nodes <- newnode(name= 'Request Extension',
                   inputs = c('Project Continuing'),
                   outputs = 'Extension of Access Implemented'
                   )
  
  nodes <- newnode(name= 'Low Risk Data',
                   inputs = c('Project Concluded')
  
                   )
  
  nodes <- newnode(name= 'High Risk Data',
                   inputs = c('Project Concluded')
  
                   )
  
  nodes <- newnode(name = 'User Creates Data Archives Package',
                   inputs = 'Low Risk Data'
                   )
  
  nodes <- newnode(name = 'Data Admin Creates Data Archives Package',
                   inputs = 'High Risk Data'
                   )
  
  nodes <- newnode(name = 'Data Admin Stores Data',
                   inputs = 'Data Admin Creates Data Archives Package',
                   outputs = c('Notify User Admin of Storage',
                     'Notify User of Storage',
                   'Notify Registries of Project Conclusion')
                   )
  
  nodes <- newnode(name= 'Data Archives Receives Data',
                   inputs = c('User Creates Data Archives Package')
                   )
  
  nodes <- newnode(name= 'Store Archive Data',
                   inputs = 'Data Archives Receives Data',
                   outputs = c('Notify User of Archive Storage',
                   'Notify Registries of Project Conclusion')
                   )
  
  nodes <- newnode(name= 'User Data Archiving',
                   inputs = 'Notify User of Archive Storage',
                   outputs = c('User Destroys Data',
                   'User Stores Data and Informs User Admin of Security')
                   )
  
  nodes <-  newnode(name = 'User Admin Records Status in ANU-User-DB',
                    inputs =
                    'User Stores Data and Informs User Admin of Security'
                    )
  
#+end_src
** COMMENT plot nodes
#+name:plotnodes
#+begin_src R :session *R* :tangle DataAccessFlowDiagram.r :exports none :eval no
  ################################################################
  # name:plotnodes
      dev.copy2pdf(file='DataAccessFlowDiagram-EndAccess.pdf')
      dev.off()
  
#+end_src


* Appendices
** COMMENT plot all nodes
#+begin_src R :session *R* :tangle no :exports none :eval no   
  
  source('DataAccessFlowDiagram.r')
  
  # NB this needs to be run with edits to the above codes 
  #dev.copy2pdf(file='DataAccessFlowDiagram-AllNodes.pdf')
  #dev.off()
  
#+end_src

** Details of Steps for Getting Access
#\includepdf{DataAccessFlowDiagram-GettingAccess.pdf}
\begin{figure}[!h]
\centering
\includegraphics[width=1.4\textwidth]{DataAccessFlowDiagram-GettingAccess.pdf}
\caption{Detailed Flow Diagram of Getting Access}
\label{fig:DataAccessFlowDiagram-GettingAccess}
\end{figure}
\clearpage
** Details of Steps to Manage Access

\begin{figure}[!h]
\centering
\includegraphics[width=1.4\textwidth]{DataAccessFlowDiagram-ManagingAccess.pdf}
\caption{Flow Diagram of Managing Access}
\label{fig:DataAccessFlowDiagram-ManagingAccess}
\end{figure}
\clearpage

** Details of Steps to End Access


\begin{figure}[!h]
\centering
\includegraphics[width=\textwidth]{DataAccessFlowDiagram-EndAccess.pdf}
\caption{Flow Diagram for Ending Access}
\label{fig:DataAccessFlowDiagram-EndAccess}
\end{figure}
\clearpage
